### ISSUE TITLE
NameError: global name 'norm' is not defined in Python3

### ISSUE THREAD

**Issue by antani** [yassinemaaroufi/MibianLib#2]
Scipy is already installed in the python3 virtualenv- 
(py33) root@www:~/nifty/quantandfinancial# apt-get install python-numpy python-scipy python-matplotlib ipython ipython-notebook python-pandas python-sympy python-nose
Reading package lists... Done
Building dependency tree
Reading state information... Done
python-nose is already the newest version.
python-numpy is already the newest version.
ipython is already the newest version.
ipython-notebook is already the newest version.
python-matplotlib is already the newest version.
python-pandas is already the newest version.
python-scipy is already the newest version.
python-sympy is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

 but I still get 
(py33) root@www:~/nifty/quantandfinancial# python3 black_scholes.py
Mibian requires scipy to work properly
Traceback (most recent call last):
  File "black_scholes.py", line 36, in <module>
    c = mibian.BS([ 6051.55 , 6000, .0007, tte], volatility=volat)
  File "/root/py33/lib/python3.3/site-packages/mibian/**init**.py", line 278, in **init**
    [self.callPrice, self.putPrice] = self._price()
  File "/root/py33/lib/python3.3/site-packages/mibian/__init__.py", line 307, in _price
    call = self.underlyingPrice \* norm.cdf(self._d1_) - \
NameError: global name 'norm' is not defined

**Comment by sidnet033** [comment]
how to resolve this?
