### ISSUE TITLE
print syntax error from Python 2.7 that doesn't work on Python 3.5

### ISSUE THREAD

**Issue by vwxyzjn** [yassinemaaroufi/MibianLib#6]
import mibian
  File "C:\Users\costa\Anaconda3\lib\site-packages\mibian__init__.py", line 11
    print 'Mibian requires scipy to work properly'
                                                 ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by yassinemaaroufi** [comment]
Hi,

Mibianlib is fixed

It was a compatibility problem with python v3

You can reinstall the library and it should work properly.

Best regards

Yassine Maaroufi
